from typing import List, Protocol

from base_qt.views.registry.models import ViewSpec


class IViewRegistry(Protocol):
    def register(self, spec: ViewSpec) -> None: ...
    def list(self) -> List[ViewSpec]: ...
    def get(self, view_id: str) -> ViewSpec: ...